export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_PENDING_FRIENDSHIP = 'USER_PENDING_FRIENDSHIP';

// Authors
export const FETCH_AUTHORS = 'FETCH_AUTHORS';

// Friends
export const SEARCH_USERS = 'SEARCH_USERS';
